import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import {
    computeCenterlinePoints,
    getBestRectangles,
    returnCenterlines,
    pointInPolygon,
} from '../utils/corridorCenterline'

// ─── Load Python EXE fixture data (ground truth) ────────────────────
// Generated by: python __tests__/fixtures/generate_exe_fixtures.py
// This runs the ACTUAL Python EXE code (centerline.py) on test polygons.
const fixtures = JSON.parse(
    readFileSync(join(__dirname, 'fixtures', 'exe_sensor_fixtures.json'), 'utf-8')
)

function getFixture(name) {
    return fixtures.tests.find(t => t.name === name)
}

// ─── Web app test data (pixel coordinates) ──────────────────────────

const northFinchley = {
    pixelsPerMesh: 4.196580544360626,
    corridorPoly: [
        { x: 667.2563065533395, y: 1347.1023547397608 },
        { x: 1208.6151967758603, y: 1347.1023547397608 },
        { x: 1208.6151967758603, y: 1410.0510629051703 },
        { x: 835.1195283277646, y: 1410.0510629051703 },
        { x: 835.1195283277646, y: 1569.5211235908741 },
        { x: 746.9913368961915, y: 1569.5211235908741 },
        { x: 746.9913368961915, y: 1410.0510629051703 },
        { x: 667.2563065533395, y: 1410.0510629051703 },
    ],
    doors: [],
    doorRoles: {},
}

const ianTest2 = {
    pixelsPerMesh: 4.260011737073032,
    corridorPoly: [
        { x: 1819.0250117301848, y: 1043.7028755828928 },
        { x: 2040.5456220579824, y: 1043.7028755828928 },
        { x: 2040.5456220579824, y: 1035.1828521087468 },
        { x: 2108.705809851151, y: 1035.1828521087468 },
        { x: 2108.705809851151, y: 1043.7028755828928 },
        { x: 2142.785903747735, y: 1043.7028755828928 },
        { x: 2142.785903747735, y: 1252.4434506994714 },
        { x: 1912.7452699457915, y: 1252.4434506994714 },
        { x: 1912.7452699457915, y: 1307.823603281421 },
        { x: 2083.1457394287127, y: 1307.823603281421 },
        { x: 2083.1457394287127, y: 1333.3836737038591 },
        { x: 2142.785903747735, y: 1333.3836737038591 },
        { x: 2142.785903747735, y: 1295.043568070202 },
        { x: 2155.5659389589546, y: 1295.043568070202 },
        { x: 2155.5659389589546, y: 1252.4434506994714 },
        { x: 2142.785903747735, y: 1252.4434506994714 },
    ],
    doors: [],
    doorRoles: {},
}

// ─── Helpers ────────────────────────────────────────────────────────

function isInsidePoly(point, poly) {
    return pointInPolygon(point.x, point.y, poly.map(p => p.x), poly.map(p => p.y))
}

function coverageGaps(sensors, poly, inset = 0.4, maxGap = 2.0, step = 0.5) {
    const polyX = poly.map(p => p.x), polyY = poly.map(p => p.y)
    const xMin = Math.min(...polyX), xMax = Math.max(...polyX)
    const yMin = Math.min(...polyY), yMax = Math.max(...polyY)

    function distToEdge(px, py) {
        let minDist = Infinity
        for (let i = 0; i < poly.length; i++) {
            const a = poly[i], b = poly[(i + 1) % poly.length]
            const dx = b.x - a.x, dy = b.y - a.y
            const lenSq = dx * dx + dy * dy
            if (lenSq === 0) continue
            let t = ((px - a.x) * dx + (py - a.y) * dy) / lenSq
            t = Math.max(0, Math.min(1, t))
            const ex = a.x + t * dx, ey = a.y + t * dy
            const d = Math.sqrt((px - ex) ** 2 + (py - ey) ** 2)
            if (d < minDist) minDist = d
        }
        return minDist
    }

    const gaps = []
    for (let x = xMin; x <= xMax; x += step) {
        for (let y = yMin; y <= yMax; y += step) {
            if (!pointInPolygon(x, y, polyX, polyY)) continue
            if (distToEdge(x, y) < inset) continue
            const nearest = Math.min(...sensors.map(s =>
                Math.sqrt((s.x - x) ** 2 + (s.y - y) ** 2)
            ))
            if (nearest > maxGap) {
                gaps.push({ x: x.toFixed(2), y: y.toFixed(2), dist: nearest.toFixed(2) })
            }
        }
    }
    return gaps
}

// ─── Test: JS getBestRectangles + returnCenterlines vs Python EXE ───
// Same input vertices, compare rectangle decomposition and sensors.

describe('JS port vs Python EXE (fixture comparison)', () => {
    for (const fixtureName of [
        'North Finchley CC_Corner',
        'North Finchley Lobby_corner',
        'North Finchley Combined',
        'Ian Test 2',
    ]) {
        describe(fixtureName, () => {
            const fixture = getFixture(fixtureName)
            let jsRects, jsSensors

            beforeAll(() => {
                const points = fixture.vertices.map(v => ({ x: v.x, y: v.y }))
                jsRects = getBestRectangles(points)
                jsSensors = returnCenterlines(jsRects, 0.5)
            })

            it('produces rectangles', () => {
                const jsCount = jsRects.length / 4
                console.log(`\n${fixtureName}: Python ${fixture.rectangle_count} rects, JS ${jsCount} rects`)
                expect(jsCount).toBeGreaterThan(0)
            })

            it('rectangle area matches polygon area (same as Python)', () => {
                // Python's area check: within 0.1m²
                const xs = fixture.vertices.map(v => v.x)
                const ys = fixture.vertices.map(v => v.y)
                let polyArea = 0
                for (let i = 0; i < xs.length; i++) {
                    const j = (i + 1) % xs.length
                    polyArea += xs[i] * ys[j] - ys[i] * xs[j]
                }
                polyArea = Math.abs(polyArea) / 2

                let rectArea = 0
                for (let i = 0; i < jsRects.length; i += 4) {
                    rectArea += (jsRects[i+1] - jsRects[i]) * (jsRects[i+3] - jsRects[i+2])
                }

                console.log(`  Polygon: ${polyArea.toFixed(2)}m², JS rects: ${rectArea.toFixed(2)}m²`)
                // Monte Carlo is nondeterministic, but area should match within tolerance
                expect(Math.abs(rectArea - polyArea)).toBeLessThan(2.0)
            })

            it('sensor count in same ballpark as Python', () => {
                console.log(`  Python: ${fixture.sensor_count} sensors, JS: ${jsSensors.length} sensors`)
                // Nondeterministic, but should be within 50%
                expect(jsSensors.length).toBeGreaterThan(fixture.sensor_count * 0.5)
                expect(jsSensors.length).toBeLessThan(fixture.sensor_count * 2)
            })

            it('every Python sensor (inside polygon) has a JS sensor within 1.5m', () => {
                const polyX = fixture.vertices.map(v => v.x)
                const polyY = fixture.vertices.map(v => v.y)
                // Only check Python sensors that are inside the polygon
                const pyInside = fixture.sensors.filter(s =>
                    pointInPolygon(s.x, s.y, polyX, polyY)
                )
                const unmatched = []
                for (const py of pyInside) {
                    const nearest = Math.min(...jsSensors.map(js =>
                        Math.sqrt((js.x - py.x) ** 2 + (js.y - py.y) ** 2)
                    ))
                    if (nearest > 1.5) {
                        unmatched.push({ py, nearest: nearest.toFixed(2) })
                    }
                }
                if (unmatched.length > 0) {
                    console.log(`  ${unmatched.length} Python sensors not matched:`)
                    unmatched.slice(0, 5).forEach(u =>
                        console.log(`    m(${u.py.x},${u.py.y}) nearest JS=${u.nearest}m`)
                    )
                }
                expect(unmatched.length).toBe(0)
            })
        })
    }
})

// ─── Test: computeCenterlinePoints (full web app pipeline) ──────────
// Compares web app output against Python EXE fixture for same corridor.

describe('computeCenterlinePoints vs Python EXE', () => {
    const projects = [
        { name: 'North Finchley', fixtureName: 'North Finchley Combined', ...northFinchley },
        { name: 'Ian Test 2', fixtureName: 'Ian Test 2', ...ianTest2 },
    ]

    for (const project of projects) {
        describe(project.name, () => {
            const fixture = getFixture(project.fixtureName)
            let webSensors, webSensorsM
            const pxPerM = project.pixelsPerMesh * 10

            beforeAll(() => {
                webSensors = computeCenterlinePoints(
                    project.corridorPoly, project.doors, project.doorRoles,
                    project.pixelsPerMesh, 0.5, 0.4
                )
                webSensorsM = webSensors.map(s => ({
                    x: Math.round(s.x / pxPerM * 10) / 10,
                    y: Math.round(s.y / pxPerM * 10) / 10,
                }))
            })

            it('produces sensors', () => {
                console.log(`\n=== ${project.name}: Web ${webSensors.length} sensors, Python ${fixture.sensor_count} ===`)
                expect(webSensors.length).toBeGreaterThan(0)
            })

            it('most sensors inside corridor polygon', () => {
                // EXE doesn't filter sensors — some may land just outside due to
                // rectangle decomposition extending beyond polygon boundary
                const outside = webSensors.filter(s => !isInsidePoly(s, project.corridorPoly))
                const pct = outside.length / webSensors.length
                console.log(`  ${outside.length}/${webSensors.length} outside polygon (${(pct*100).toFixed(0)}%)`)
                expect(pct).toBeLessThan(0.2) // less than 20% outside
            })

            it('every Python sensor (inside polygon) has a web sensor within 1.5m', () => {
                const polyX = fixture.vertices.map(v => v.x)
                const polyY = fixture.vertices.map(v => v.y)
                const pyInside = fixture.sensors.filter(s =>
                    pointInPolygon(s.x, s.y, polyX, polyY)
                )
                const unmatched = []
                for (const py of pyInside) {
                    const nearest = Math.min(...webSensorsM.map(w =>
                        Math.sqrt((w.x - py.x) ** 2 + (w.y - py.y) ** 2)
                    ))
                    if (nearest > 1.5) {
                        unmatched.push({ py, nearest: nearest.toFixed(2) })
                    }
                }
                if (unmatched.length > 0) {
                    console.log(`  ${unmatched.length} Python sensors not covered by web app:`)
                    unmatched.slice(0, 5).forEach(u =>
                        console.log(`    m(${u.py.x},${u.py.y}) nearest web=${u.nearest}m`)
                    )
                }
                expect(unmatched.length).toBe(0)
            })

            it('no coverage gaps >2m in corridor interior', () => {
                const insetPx = 0.4 * pxPerM
                const gaps = coverageGaps(webSensors, project.corridorPoly, insetPx, 2.0 * pxPerM, 0.5 * pxPerM)
                if (gaps.length > 0) {
                    console.log(`  ${gaps.length} coverage gaps:`)
                    gaps.slice(0, 5).forEach(g =>
                        console.log(`    m(${(parseFloat(g.x)/pxPerM).toFixed(2)},${(parseFloat(g.y)/pxPerM).toFixed(2)}) nearest=${(parseFloat(g.dist)/pxPerM).toFixed(2)}m`)
                    )
                }
                expect(gaps.length).toBe(0)
            })

            it('sensor positions', () => {
                console.log(`\n--- Python EXE (inside polygon only) ---`)
                const polyX = fixture.vertices.map(v => v.x)
                const polyY = fixture.vertices.map(v => v.y)
                fixture.sensors
                    .filter(s => pointInPolygon(s.x, s.y, polyX, polyY))
                    .forEach((s, i) => console.log(`  ${i}: m(${s.x},${s.y})`))
                console.log(`\n--- Web app ---`)
                webSensorsM.forEach((s, i) => console.log(`  ${i}: m(${s.x},${s.y})`))
            })
        })
    }
})
